#-sudo: required
#-dist: xenial

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

    packages:
    # install toolchains
    - gcc-5
    - g++-5


language: python
python:
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
#compiler:
#  - gcc-5.4

# command to install dependencies
install: 
  - CC="gcc-5" CCX="g++-5" python3 setup.py install

# command to run tests
script: nosetests
