language: python
python:
  - "3.5"

before_install:
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  #- sudo apt-get install gcc-4.9 g++-4.9 gcc-5 g++-5 -y
  - sudo apt-get install clang-3.9 -y  #clang-3.6 clang-3.7 clang-3.8 clang-3.9 -y
  # set compilers
  - export CC="clang-3.9"
  - export CXX="clang-3.9"

# command to install dependencies
install: 
  - echo $CC 
  - python3 setup.py install

# command to run tests
#script: nosetests
