
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - valgrind
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test
os: linux
compiler: gcc-6
env: 
  - CC=g++-6 CC=g++-c

# command to install dependencies
install: 
  # adding swap because travis default ram is not enought
  - dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
  - mkswap /var/swap.img
  - swapon /var/swap.img
  # set compilers
  - echo $CC 
  - python3 setup.py install

# command to run tests
script: nosetests
