sudo: required
dist: focal
language: python

git:
  #depth: 1
  submodules: true

cache:
  apt: true
  pip: true

addons:
  apt:
    packages: &base_deps
    - build-essential 
    - cython
    - libantlr4-runtime-dev
    - antlr4

matrix:
  include:
    - name: "Python 2.7 gcc-8"
      python: 2.7
      env: CC=gcc-8 CXX=g++-8
      addons:
        apt:
          packages:
            - *base_deps
            - g++-8
            - gcc-8

    - name: "Python 3.8 gcc-9 Debug+Coverage"
      python: 3.8
      env: CC=gcc-9 CXX=g++-9 BUILD_ARGS="--build-type Debug -- -DCODE_COVERAGE=ON" CODE_COVERAGE=1
      addons:
        apt:
          packages:
            - *base_deps
            - g++-9
            - gcc-9

    - name: "Python 3.8 gcc-9 (deploy on tag)"
      python: 3.8
      env: CC=gcc-9 CXX=g++-9 DO_DELPLOY=1
      addons:
        apt:
          packages:
            - *base_deps
            - g++-9
            - gcc-9

    - name: "Python 3.8 gcc-9 from pip"
      python: 3.8
      env: CC=gcc-9 CXX=g++-9 FROM_PIP=1
      addons:
        apt:
          packages:
            - *base_deps
            - g++-9
            - gcc-9

# command to install dependencies
install:
- if [ "$CODE_COVERAGE" == "1" ]; then
    sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 10;
    sudo apt install -y lcov;
    gem install coveralls-lcov;
  fi

- pip install jupyter
- if [ "$FROM_PIP" == "1" ]; then
    pip install hdlConvertor;
    export PIP_GIT_TAG=$(pip show hdlConvertor | sed -n "s/^Version:\s*\(\S*\)$/\1/p");
    git checkout "v$PIP_GIT_TAG"
  else
    pip install git+https://github.com/Nic30/hdlConvertorAst.git ;
    pip install -r requirements.txt ;
    python setup.py build -j$(nproc) $BUILD_ARGS ;
    python setup.py install $BUILD_ARGS ;
  fi

script: 
  - python setup.py test $BUILD_ARGS # the scikit-build automatically executes setup.py develop which requires access to installation dir

after_success:
- if [ "$CODE_COVERAGE" == "1" ]; then
    lcov --compat-libtool --directory . --capture --output-file coverage.info.raw ;
    lcov --remove coverage.info.raw -o coverage.info '/usr/*' '*_skbuild/*' ;
    coveralls-lcov coverage.info ;
  fi

deploy:
  provider: pypi
  user: nic30
  password:
    secure: jMuoFXUX5kopaE0ezjl6NUtxAmr8SyKpRyqZQtv3TISOCCmyenqeMR3EVckEsslC5NpQOVDQHagevooo2Ysfpu6WaFll+QJgkvB7yvt3ZHNcXj9YITTpjJNmPF58jch5cjb+kFvMvPnvOnbasBtB+KRiV4tmGRXrgP0Qg7mamVnafo3Krq0OY5hAE+fK2WhFfkyZ8xdo1M794mHf9fIRcmT9c9D8cMatYjjbq724g3OJ8wlIWxDfoa012D+G2IdZOd5+aMkNMOPd504ZnUj40T39kVsgXv0kIx42Y/Wz4Om53UT2GwTBllERq4u5nDB6A4NiVTwpx4g9+r6rCjIBtX11bRgMaDCp7Jdn6KWOsKhvQtU4u2ZGUdIRCrIoJj0NInCfedKnF0FqYA4BC7HgbFCIUnpyKxR/uU0Vz7tD/jW4vP5tr4PcgQ2eTRM5eVJZ3dYoxzlFh2MzmjXA4+MamFVCRjmzDdvaBafEvYlyUUq0D2MQ2hMwjyNlcEIKW4eOi2LaVgdwJsKbDQHc66oVDQRRYu77yFW9XGhwFoTEn0km5TTVah0d9JwvqVzWo4R33FexuthR7pHQbIe7Shw6HKpV6JfbLtvYSLLBXK8UGlW7PXYQtAZN81fwZzXd+2RwCr8otJeGzNIHug0HjK4S0CYCx4HNi0qHXOl5B+DiPuw=
  on:
    tags: true
    branch: master
    condition: $DO_DELPLOY = 1
