
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - valgrind
      - clang-3.9
    sources: &sources
      - ubuntu-toolchain-r-test
os: linux
env: 
  - CC=clang-3.9 CC=clang-3.9

# command to install dependencies
install: 
  # set compilers
  - echo $CC 
  - python3 setup.py install

# command to run tests
script: nosetests
