sudo: required
dist: trusty

language: python

cache:
  apt: true

# clang is required because there is not enought ram for gcc
compiler: clang
python:
  - "3.5"
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         #- llvm-toolchain-precise-3.9
      packages:
         - g++-5
         #- clang-3.9
#env: CC=clang-3.9 CXX=clang-3.9
env: CC=g++-5 CXX=g++-5 
#CFLAGS=-stdlib=libc++ CXXFLAGS=-stdlib=libc++


# command to install dependencies
install:
  - free 
  - echo $CC 
  - python3 setup.py install

# command to run tests
script: nosetests
