#-sudo: required
#-dist: xenial

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6

language: python
python:
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
#compiler:
#  - gcc-5.4

# command to install dependencies
install: 
  - python3 setup.py install

# command to run tests
script: nosetests
