
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - valgrind
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test
os: linux
compiler: gcc-6

#env:
#  - CC=gcc-5 CCX=g++-5 COMPILER=g++-5

# command to install dependencies
install: 
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CC=${COMPILER}; fi
  - gcc --version
  - echo $CC 
  - python3 setup.py install

# command to run tests
script: nosetests
