-platforms:
-  - name: ubuntu-16.04

language: python
python:
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
#compiler:
#  - gcc-5.4

# command to install dependencies
install: 
  - python3 setup.py install

# command to run tests
script: nosetests
