# if trusty is not used compilation is killed (out or mem)
sudo: required
dist: trusty

language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - "nightly"

git:
  depth: 1

cache:
  apt: true

# clang is required because there is not enought ram for gcc
compiler: gcc

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         #- llvm-toolchain-precise-3.9
      packages:
         - g++-5
         #- clang-3.9
#env: CC=clang-3.9 CXX=clang-3.9
env: CC=g++-5 CXX=g++-5 


# command to install dependencies
install:
  - python3 setup.py install
  #- travis_wait "python3 setup.py install"

# command to run tests
script: nosetests
