addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

    packages:
    # install toolchains
    - gcc-5.4
    - g++-5.4


language: python
python:
  - "3.5"

compiler:
  - gcc-5.4

env:
  - CC=gcc-5.4 CCX=g++-5.4

# command to install dependencies
install: 
  - python3 setup.py install

# command to run tests
script: nosetests
