language: python
python:
  - "3.5"


compiler: clang
addons:
     apt:
       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
        packages: ['clang-3.9', 'valgrind']
env: COMPILER=clang++-3.9  CC=clang-3.9 CXX=clang-3.9

# command to install dependencies
install: 
  - echo $CC 
  - python3 setup.py install

# command to run tests
#script: nosetests
