language: python


# clang is required because there is not enought ram for gcc
compiler: clang
python:
  - "3.5"
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         - llvm-toolchain-precise-3.8
      packages:
         - g++-6
         - clang-3.8
env: CC=clang-3.8 CXX=clang-3.8 CFLAGS=-stdlib=libc++ CXXFLAGS=-stdlib=libc++


# command to install dependencies
install: 
  - echo $CC 
  - python3 setup.py install

# command to run tests
script: nosetests
