
matrix:
    # Test gcc-5.0: C++11
    - env: GCC_VERSION=5 CPP=11 LIBCXX=Off
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

language: python
python:
  - "3.5"

# command to install dependencies
install: 
  - python3 setup.py install

# command to run tests
script: nosetests
