version: 2.1

orbs:
  python: circleci/python@0.2.1
  py: nic30/python-all-in-1@0.2.8

jobs:
  install-and-test:
    executor: python/default
    resource_class: small
    steps:
      - checkout
      # - python/load-cache
      - run: sudo apt install -y build-essential cython libantlr4-runtime-dev antlr4 cmake
      - run: pip install jupyter
      - py/install-gcov
      - py/install-setup-py
      # - python/save-cache
      - py/test-and-coverage
      - py/coverage-upload-lcov

  deploy:
    executor: python/default
    steps:
      - py/deploy-pypi

workflows:
  main:
    jobs:
      - install-and-test
      - deploy:
         requires:
           - install-and-test
         filters:
           tags:
             only: /v[0-9]+(\.[0-9]+)*/
           branches:
             ignore: /.*/
