version: 2.1

orbs:
  python: circleci/python@0.2.1
  py: nic30/python-all-in-1@0.2.8

jobs:
  install-and-test:
    # executor: python/default
    resource_class: medium
    docker:
      - image: gcc:10
    steps:
      - checkout
      # - python/load-cache
      - run: apt install -y sudo
      - run: sudo apt install -y build-essential cython libantlr4-runtime-dev antlr4 cmake python3-pip
      - run:
          command: |
            sudo ln -s /usr/bin/pip3 /usr/bin/pip 
            sudo ln -s /usr/bin/python3 /usr/bin/python

      - run: pip install jupyter
      - py/install-gcov
      - py/install-setup-py
      # - python/save-cache
      - py/test-and-coverage
      - py/coverage-upload-lcov

  deploy:
    # executor: python/default
    docker:
      - image: gcc:10
    steps:
      - py/deploy-pypi

workflows:
  main:
    jobs:
      - install-and-test
      - deploy:
         requires:
           - install-and-test
         filters:
           tags:
             only: /v[0-9]+(\.[0-9]+)*/
           branches:
             ignore: /.*/
