version: 2.1

orbs:
  python: circleci/python@0.2.1
  py: nic30/python-all-in-1@0.2.9

jobs:
  install-and-test:
    # executor: python/default
    resource_class: medium
    docker:
      - image: circleci/buildpack-deps:groovy
    steps:
      - checkout
      # - python/load-cache
      - run: sudo apt install -y build-essential libantlr4-runtime-dev antlr4 cmake ninja-build python3-pip
      - run:
          command: |
            sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10;
            sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10;

      - run:
          command: |
            gcc -v;
            python --version;
            cmake --version;

      - run: pip install jupyter
      - py/install-gcov
      - py/install-setup-py:
          rm-package-dir: true
      # - python/save-cache
      - py/test-and-coverage:
          coverage: false
      - py/coverage-upload-lcov

  deploy:
    # executor: python/default
    docker:
      - image: circleci/buildpack-deps:groovy
    steps:
      - py/deploy-pypi

workflows:
  main:
    jobs:
      - install-and-test
      - deploy:
         requires:
           - install-and-test
         filters:
           tags:
             only: /v[0-9]+(\.[0-9]+)*/
           branches:
             ignore: /.*/
